#Author: Justin Cain @AffinityForFun
CC			= g++
FLAGS		= -Wall -std=c++11
TESTOPTIONS = time
#valgrind --leak-check=yes

final : bitwiseio huffman binarynode
	$(CC) $(FLAGS) Huffman.o BitwiseIO.o HuffmanBinaryNode.o -o Huffman

huffman : 
	$(CC) $(FLAGS) -c Huffman.cpp
	
bitwiseio :
	$(CC) $(FLAGS) -c BitwiseIO.cpp
	
binarynode :
	$(CC) $(FLAGS) -c HuffmanBinaryNode.cpp
	
remake : clear final

clear : clean
	clear
	
clean :
	rm -f ./Huffman Huffman.o BitwiseIO.o HuffmanBinaryNode.o TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT

test : 
	$(TESTOPTIONS) ./Huffman encode input/readable.test TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	diff input/readable.test TESTING_OUTPUT_DECODE.OUTPUT
	ls -l TESTING_OUTPUT_ENCODE.OUTPUT
	rm TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT

	
testfake : 	
	$(TESTOPTIONS) ./Huffman encode notreal.input TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode input/readable.test TESTING_OUTPUT_DECODE.OUTPUT
	rm TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	
testdouble : 
	./Huffman encode input/1MB.test TESTING_OUTPUT_ENCODE1.OUTPUT
	./Huffman encode TESTING_OUTPUT_ENCODE1.OUTPUT TESTING_OUTPUT_ENCODE2.OUTPUT
	./Huffman decode TESTING_OUTPUT_ENCODE2.OUTPUT TESTING_OUTPUT_DECODE2.OUTPUT
	./Huffman decode TESTING_OUTPUT_DECODE2.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	ls -l *.OUTPUT
	diff input/1MB.test TESTING_OUTPUT_DECODE.OUTPUT
	rm *.OUTPUT
	
testmore : 
	$(TESTOPTIONS) ./Huffman encode input/empty.test TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	ls -l TESTING_OUTPUT_ENCODE.OUTPUT
	diff input/empty.test TESTING_OUTPUT_DECODE.OUTPUT
	
	$(TESTOPTIONS) ./Huffman encode input/1MB.test TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	ls -l TESTING_OUTPUT_ENCODE.OUTPUT
	diff input/1MB.test TESTING_OUTPUT_DECODE.OUTPUT
	
	$(TESTOPTIONS) ./Huffman encode input/10MB.test TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	ls -l TESTING_OUTPUT_ENCODE.OUTPUT
	diff input/10MB.test TESTING_OUTPUT_DECODE.OUTPUT
	
	$(TESTOPTIONS) ./Huffman encode input/137MB.test TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	diff input/137MB.test TESTING_OUTPUT_DECODE.OUTPUT
	ls -l TESTING_OUTPUT_ENCODE.OUTPUT
	rm TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	
testlarge : 
	$(TESTOPTIONS) ./Huffman encode input/1GB.test TESTING_OUTPUT_ENCODE.OUTPUT
	$(TESTOPTIONS) ./Huffman decode TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	diff input/1GB.test TESTING_OUTPUT_DECODE.OUTPUT
	ls -l TESTING_OUTPUT_ENCODE.OUTPUT
	rm TESTING_OUTPUT_ENCODE.OUTPUT TESTING_OUTPUT_DECODE.OUTPUT
	
	